-- Add ACDR to all table in a schema
BEGIN
  FOR T IN (SELECT OWNER, TABLE_NAME FROM CDB_TABLES WHERE OWNER IN ('HR'))
  LOOP
    DBMS_GOLDENGATE_ADM.ADD_AUTO_CDR(
        SCHEMA_NAME => T.OWNER,
        TABLE_NAME  => T.TABLE_NAME,
        RECORD_CONFLICTS => TRUE,
        ADDITIONAL_OPTIONS => 0);   
            -- O -> LATEST_TIMESTAMP_RESOLUTION
            -- 1 -> EARLIEST_TIMESTAMP_RESOLUTION
  END LOOP;
END;

select * from DBA_GG_AUTO_CDR_TABLES;


--  Remove ACDR to all tables in a schema
BEGIN
  FOR T IN (SELECT OWNER, TABLE_NAME FROM CDB_TABLES WHERE TABLE_NAME NOT LIKE 'DT$%' AND OWNER IN ('HR'))
  LOOP
    DBMS_GOLDENGATE_ADM.REMOVE_AUTO_CDR(
        SCHEMA_NAME => T.OWNER,
        TABLE_NAME  => T.TABLE_NAME);
  END LOOP;
END;

select * from DBA_GG_AUTO_CDR_TABLES;


