{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Process Status (West -> East)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resource-status_running\")\n  |> filter(fn: (r) => r[\"resource-name\"] == \"RWEST\" or r[\"resource-name\"] == \"EWEST\" )\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Process Status (East -> West)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resource-status_running\")\n  |> filter(fn: (r) => r[\"resource-name\"] == \"REAST\" or r[\"resource-name\"] == \"EEAST\" )\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "SEQ Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-output_trail-seq\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-output_trail-rba\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Seq Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-input_trail-seq\")\n  |> filter(fn: (r) => r[\"processName\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-input_trail-rba\")\n  |> filter(fn: (r) => r[\"processName\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SEQ Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-output_trail-seq\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-output_trail-rba\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Seq Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-input_trail-seq\")\n  |> filter(fn: (r) => r[\"processName\"] == \"REAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trail-input_trail-rba\")\n  |> filter(fn: (r) => r[\"processName\"] == \"REAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Heartbeat Lag",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heartbeat-timings_heartbeat-lag\")\n  |> filter(fn: (r) => r[\"heartbeat-name\"] == \"EEAST\" or r[\"heartbeat-name\"] == \"EWEST\" or r[\"heartbeat-name\"] == \"REAST\" or r[\"heartbeat-name\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Last Operation Lag",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\" or r[\"processName\"] == \"EWEST\" or r[\"processName\"] == \"REAST\" or r[\"processName\"] == \"RWEST\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position-er_last-operation-lag\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Updates EWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-updates\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Deletes EWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-deletes\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inserts EWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-inserts\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Updates RWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-updates\")\n  |> filter(fn: (r) => r[\"processName\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Deletes RWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-deletes\")\n  |> filter(fn: (r) => r[\"processName\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inserts RWEST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-inserts\")\n  |> filter(fn: (r) => r[\"processName\"] == \"RWEST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Updates EEAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-updates\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Deletes EEAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-deletes\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inserts EEAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-extract_mapped-total-inserts\")\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Updates REAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-updates\")\n  |> filter(fn: (r) => r[\"processName\"] == \"REAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Deletes REAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-deletes\")\n  |> filter(fn: (r) => r[\"processName\"] == \"REAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inserts REAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics-replicat_mapped-total-inserts\")\n  |> filter(fn: (r) => r[\"processName\"] == \"REAST\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Last Ops Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"processName\"] == \"EEAST\" or r[\"processName\"] == \"EWEST\" or r[\"processName\"] == \"REAST\" or r[\"processName\"] == \"RWEST\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position-er_last-operation-lag\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"goldengate-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_idle\")\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}